### ISSUE TITLE
building modular app

### ISSUE THREAD

**Issue by shalkam** [meldio/meldio#6]
Hi,
I've just got started with meldio and it looks great but I have this one question in mind.
I really don't know about the `.sdl` extension for `schema.sdl` but this file seems to be the main file defining everything.
But what if I want to build a modular with multiple types and each type is located in a separate directory, is there a way to bootstrap everything in one file?

regards,
Mostafa

**Comment by nemanja-stanarevic** [comment]
Currently, all of the types are defined in one schema file since individual type definitions are typically rather small. You can, however, define types in individual files/directories and have a build step that concatenates them together into `schema.sdl`.

Thanks, looking forward to hear more about what you are building
